---
- name: Deploy a Web Page
  hosts: webservers
  become: yes
  tasks:
    - name: Copy index.html to the web server document root
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
        enabled: yes
