- name: Install and Configure Apache
  hosts: localhost
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Copy HTML file
      copy:
        src: templates/index.html
        dest: /var/www/html/index.html

    - name: Copy static assets
      copy:
        src: static/
        dest: /var/www/html/static/
        remote_src: no

